spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username:
    password:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  sql:
#    init:
#      mode: always
  jpa:
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

    mvc:
      hiddenmethod:
        filter:
          enabled: true

###Logging Levels
  # Disable the default loggers
  logging:
    level:
      org: WARN
      blog: WARN

  #Show SQL executed with parameter bindings
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name:

